# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-11-arm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.40"
          distribution: strawberry
      
      # Runs a single command using the runners shell
      - name: Setup msvc
        uses:  ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64
          toolset: 14.43
          vsversion: 2022
      
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git '${{ github.workspace }}/vcpkg'
          cd '${{ github.workspace }}/vcpkg'
          ./bootstrap-vcpkg.sh

      - name: Install Packages
        run: | 
          cd '${{ github.workspace }}/vcpkg'
          vcpkg.exe install --triplet=arm64-windows libxml2 lz4 pkgconf zlib--debug
